In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

# create array using numpy
# create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [24]:
print(arr1.reshape(5,1))
arr1.reshape(1,5)

[[1]
 [2]
 [3]
 [4]
 [5]]


array([[1, 2, 3, 4, 5]])

In [30]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [31]:
arr2.shape

(2, 5)

In [38]:
print(np.arange(0,10,2).reshape(5,1))

[[0]
 [2]
 [4]
 [6]
 [8]]


In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [57]:
# Numpy Vectorized Operation-:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1- arr2)
print(arr1* arr2)
print(arr1/ arr2)
print(arr1% arr2)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1 2 3 4 5]


In [ ]:
# Universal Function-:
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))

# (e = 2.71828…, the natural constant)
# Computes e^x for every element
print(np.exp(arr))

# Computes sin(x) for each element
# (directly in radians)
print(np.sin(arr))

# Computes ln(x) = natural log
# (It is log base e)
print(np.log(arr))

# It is log base 2
print(np.log2(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[1.         1.5849625  2.         2.32192809 2.5849625 ]


In [117]:
# Array slicing and indexing-:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Array: \n", arr)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)
print(arr.shape)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
2
int64
8
(3, 4)


In [103]:
print(arr[0,3])
print(arr[0][3])
print(arr[1:,2:])


4
4
[[ 7  8]
 [11 12]]


In [108]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [111]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [118]:
# Modigy array elements-:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [121]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [129]:
# Statistical concepts -- Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])


# Calculation of mean and standard deviation-:
mean = np.mean(data)
print(mean)
std_dev = np.std(data)
print(std_dev)

normalized_data = (data - mean)/ std_dev
print("Normalized Data: ", normalized_data)

3.0
1.4142135623730951
Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [134]:
import math
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))
print(math.sqrt(np.var(data)))


5.5
5.5
2.8722813232690143
8.25
2.8722813232690143


In [147]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

print((data>=5) & (data<=8))
print(data[(data>=5) & (data<=8)])
print(data[(data>=5) | (data<=8)])
print(data[~((data>=5) | (data<=8))])

[False False False False  True  True  True  True False False]
[5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[]


In [ ]:
# and, or, not → only for single booleans, NOT arrays

# NumPy arrays = many booleans → Python can't decide True/False

# Therefore NumPy uses bitwise operators (&, |, ~) of Python for logical conditions