### Linear Regression

In [1]:
# diabetes dataset-:
from sklearn.datasets import load_diabetes

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [3]:
df = load_diabetes()

In [4]:
type(df)

sklearn.utils._bunch.Bunch

In [5]:
df

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142.

In [6]:
dataset = pd.DataFrame(df.data)
dataset.columns = df.feature_names
dataset.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641


In [7]:
# Target = what the model is trying to predict.
dataset['Diabetes Progression after a year'] = df.target

In [8]:
dataset.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Diabetes Progression after a year
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [9]:
#  Dividing the dataset into independent and dependnet features-:
X = dataset.iloc[:,:-1] #independent features
y = dataset.iloc[:,-1] #dependent features

In [10]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641


In [11]:
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: Diabetes Progression after a year, dtype: float64

In [12]:
# Linear Regression-:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
lin_reg = LinearRegression()

# cross_val_score with neg_mean_squared_error calculates the model’s mean squared error using cross-validation. Sklearn returns it as negative because it expects higher scores to be better. To get normal MSE, we simply take the negative of these values.

# MSE = Mean Squared Error = average of squared differences between predictions and real values.
# Smaller MSE → better model
# Bigger MSE → worse model

mse = cross_val_score(lin_reg,X,y,scoring='neg_mean_squared_error',cv=5) 
# mse (Mean Square Error)

# This line calculates the Mean Squared Error (MSE) of the linear regression model using 5-fold cross-validation.
# cross_val_score splits the data into 5 parts, trains on 4, tests on 1, and repeats for all folds.
# neg_mean_squared_error is used because sklearn (cross_val_score) expects higher scores to be better; the negative values can be converted back to normal MSE by multiplying by −1.

In [13]:
mse

array([-2779.92344921, -3028.83633883, -3237.6875877 , -3008.74648884,
       -2910.21268776])

In [14]:
mean_mse = np.mean(mse)
actual_mean_mse = -1*mean_mse
# The mean MSE of 2993.08 represents the average squared error of the model’s predictions across all 5 folds in cross-validation. Smaller MSE means better performance.
actual_mean_mse

np.float64(2993.0813104693307)

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [16]:
lin_reg = LinearRegression()
# **The `fit()` method is used to train the model by learning parameters from the training data.**
lin_reg.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [17]:
lin_reg.predict(X_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [18]:
# To make predictions, first train the linear regression model using fit(), then pass new input data as a 2D array to predict(). The output is the predicted target value.

In [19]:
lin_reg.predict([[0.05, -0.02, 0.03, -0.01, 0.04, -0.03, 0.02, -0.01, 0.06, -0.02]])

c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([161.78823405])

In [20]:
#  test_size=0.2 => 80% → training
#                              20% → testing

# Without random_state → data is split randomly each time
# With random_state=42 → split is reproducible

# Helps in:
# Debugging
# Comparing models
# Getting same results every run

### Ridge Regression

In [21]:
# In Linear Regression -: We cannot do HyperParameter tuning but In ridge Regression we can do HyperParameter Tuning.

In [22]:
from sklearn.linear_model import Ridge
# Hyper-Parameter Tuning-:
from sklearn.model_selection import GridSearchCV

In [23]:
ridge = Ridge()
params=[{'alpha':[1e-15, 1e-10,1e-8,1e-3,1e-2, 1,5,10,20]}]

# GridSearchCV exhaustively searches over a grid of hyperparameters using cross-validation and selects the combination that optimizes a given scoring metric.

# Grid Search with Cross-Validation
# 🔹 Grid → a grid of hyperparameter values
# 🔹 Search → exhaustively try all combinations
# 🔹 CV → Cross-Validation

ridge_regressor = GridSearchCV(estimator=ridge, param_grid= params,scoring='neg_mean_squared_error', cv=5)

# estimator → what to train
# param_grid → what to try
# cv → how to validate
# scoring → what “best” means
ridge_regressor


,estimator,Ridge()
,param_grid,"[{'alpha': [1e-15, 1e-10, ...]}]"
,scoring,'neg_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,1.0


In [24]:
ridge_regressor.fit(X,y)

,estimator,Ridge()
,param_grid,"[{'alpha': [1e-15, 1e-10, ...]}]"
,scoring,'neg_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,0.001


In [25]:
ridge_regressor.best_params_     # Best alpha
ridge_regressor.best_score_      # Best negative MSE
ridge_regressor.best_estimator_  # Final trained Ridge model

,alpha,0.001
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [26]:
ridge_regressor.best_params_     # Best alpha

{'alpha': 0.001}

In [27]:
# best_score_ returns negative MSE. Multiplying it by −1 gives the actual MSE, and the closer this value is to zero, the better the model’s performance.

ridge_regressor.best_score_      # Best negative MSE

np.float64(-2993.0661546538704)

In [28]:
ridge_regressor.best_estimator_  # Final trained Ridge model

,alpha,0.001
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [29]:
# fit_intercept in Linear Models (Ridge, Lasso, LinearRegression)
# fit_intercept is a parameter that controls whether the model should calculate the intercept (bias) term 
# 𝑏
# b in the linear equation:
# y=w1​x1 ​+  w2​x2  ​+  ⋯  +  wn​xn  ​+  b


# fit_intercept=True → Learn bias from data
# fit_intercept=False → Assume bias = 0 (data is already centered)

# Why it matters
# If data is not centered, you usually want True
# If data is already centered (mean = 0), False avoids unnecessary computation

In [30]:
# MSE -:
# Linear Regression -:  np.float64(2993.0813104693307)
# Ridge Regression -:  np.float64(2993.0661546538704)

### Lasso Regression

In [31]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

lasso = Lasso()
params = {'alpha':[1e-15, 1e-10, 1e-8, 1e-3, 1e-2,1,5,10,20,30,35,40,45,50,55,100]}

lasso_regressor = GridSearchCV(lasso, params, scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X,y)

c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.122e+05, tolerance: 2.153e+02
  model = cd_fast.enet_coordinate_descent(
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.004e+05, tolerance: 2.044e+02
  model = cd_fast.enet_coordinate_descent(
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consi

,estimator,Lasso()
,param_grid,"{'alpha': [1e-15, 1e-10, ...]}"
,scoring,'neg_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,1e-08


In [32]:
lasso_regressor.best_params_

{'alpha': 1e-08}

In [33]:
lasso_regressor.best_score_

np.float64(-2993.0813092745934)

In [34]:
lasso_regressor.best_estimator_

,alpha,1e-08
,fit_intercept,True
,precompute,False
,copy_X,True
,max_iter,1000
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [35]:
# MSE -:
# Linear Regression -:  np.float64(2993.0813104693307)
# Ridge Regression -:  np.float64(2993.0661546538704)
# Lasso Regression -:  np.float64(2993.0813092745934)

Rige regression gives lowest MSE. So; we will SELECT this algorithm for Diabetes Prediciton

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [37]:
# Linear Regression-:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

mse = cross_val_score(lin_reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5) 

mean_mse = np.mean(mse)
actual_mean_mse = -1*mean_mse
actual_mean_mse

np.float64(3174.366621294572)

In [38]:
ridge = Ridge()
params=[{'alpha':[1e-15, 1e-10,1e-8,1e-3,1e-2, 1,5,10,20]}]

ridge_regressor = GridSearchCV(estimator=ridge, param_grid= params,scoring='neg_mean_squared_error', cv=5)
ridge_regressor.fit(X_train,y_train)
ridge_regressor.best_score_

np.float64(-3174.134456285971)

In [39]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

lasso = Lasso()
params = {'alpha':[1e-15, 1e-10, 1e-8, 1e-3, 1e-2,1,5,10,20,30,35,40,45,50,55,100]}

lasso_regressor = GridSearchCV(lasso, params, scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X_train,y_train)
lasso_regressor.best_score_

c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.506e+05, tolerance: 1.419e+02
  model = cd_fast.enet_coordinate_descent(
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.402e+05, tolerance: 1.461e+02
  model = cd_fast.enet_coordinate_descent(
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consi

np.float64(-3173.4303439506666)

In [40]:
y_pred_linear = lin_reg.predict(X_test)
y_pred_ridge = ridge_regressor.predict(X_test)
y_pred_lasso = lasso_regressor.predict(X_test)

### r Square-:

In [41]:
from sklearn.metrics import r2_score

r2_score1 = r2_score(y_test,y_pred_linear)
r2_score2 = r2_score(y_test,y_pred_ridge)
r2_score3 = r2_score(y_test,y_pred_lasso)

In [42]:
print(r2_score1)
print(r2_score2)
print(r2_score3)

0.510394257282125
0.509936866639491
0.5104068358680736


### Adjusted R-square

In [43]:
X_test.shape

(146, 10)

In [44]:
n = X_test.shape[0]   # number of samples
p = X_test.shape[1]   # number of features

adjusted_r2_1 = 1 - (1 - r2_score1) * (n - 1) / (n - p - 1)
adjusted_r2_2 = 1 - (1 - r2_score2) * (n - 1) / (n - p - 1)
adjusted_r2_3 = 1 - (1 - r2_score3) * (n - 1) / (n - p - 1)
print("Adjusted R² (Linear):", adjusted_r2_1)
print("Adjusted R² (Ridge):", adjusted_r2_2)
print("Adjusted R² (Lasso):", adjusted_r2_3)

Adjusted R² (Linear): 0.47412716522894893
Adjusted R² (Ridge): 0.4736358937979718
Adjusted R² (Lasso): 0.4741406755620049


In [45]:
# For Adjusted R² (and R²):

# Closer to 1 → better model performance
# Means the model explains most of the variance in the target.

# Closer to 0 → poor performance
# Model explains very little of the variance.

# Can be negative
# Means the model is worse than just predicting the mean of y.

### Logistic Regression

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer

In [47]:
df = load_breast_cancer()
# Independent features-:
X = pd.DataFrame(data=df['data'], columns=df['feature_names'])
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [48]:
# Dependent Feature-:
y = pd.DataFrame(df['target'])

In [49]:
y.columns = ["Cancer Predicted"]
y

,Cancer Predicted
0,0
1,0
2,0
3,0
4,0
...,...
564,0
565,0
566,0
567,0


In [50]:
y['Cancer Predicted'].value_counts()

Cancer Predicted
1    357
0    212
Name: count, dtype: int64

In [51]:
# | Parameter           | Meaning (simple words)                 |
# | penalty           | How much to control overfitting        |
# | C                    | How strict the control is              |
# | solver             | Method to find the best answer         |
# | max_iter         | How long the model is allowed to think |
# | fit_intercept    | Whether to learn starting point (bias) |
# | class_weight   | Give extra importance to rare class    |
# | multi_class      | Binary or multi-class decision         |
# | l1_ratio            | Mix of L1 & L2 (ElasticNet only)       |
# | random_state   | Same result every time                 |

In [52]:
# C controls regularization strength in Logistic Regression -:

# Higher C means less regularization, so the model fits training data very closely and may overfit due to OUTLIERS.
# Lower C adds more regularization, making the model simpler and better at generalizing.

In [53]:
# max_iter sets the maximum number of iterations the model is allowed to run while learning.

# In simple words (for notes):
# It limits how long the model tries to find the best solution
# If too low → model may not converge (poor results)
# If higher → gives the model more time to learn

# 👉 Use: Increase max_iter when you get convergence warnings.

In [54]:
# train test split-:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [55]:
params = [{'C':[1,5,10]},{'max_iter':[100,150]}]

In [56]:
model1 = LogisticRegression(C=100,max_iter=100)

In [57]:
model = GridSearchCV(model1,param_grid=params,scoring='f1',cv=5)

In [58]:
model.fit(X_train,y_train)

c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Omkar Raut\Desktop\DataSceince\venv1\Lib\site-packages\sklearn\utils\validation.py:1406: DataCo

,estimator,LogisticRegression(C=100)
,param_grid,"[{'C': [1, 5, ...]}, {'max_iter': [100, 150]}]"
,scoring,'f1'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [59]:
model.best_params_

{'max_iter': 150}

In [60]:
model.best_score_

np.float64(0.9598077001616112)

In [61]:
y_pred = model.predict(X_test)

In [62]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1])

In [63]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [64]:
confusion_matrix(y_pred=y_pred,y_true=y_test)

array([[ 64,   3],
       [  3, 118]])

In [65]:
accuracy_score(y_true=y_test,y_pred=y_pred)

0.9680851063829787

In [66]:
print(classification_report(y_true=y_test,y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        67
           1       0.98      0.98      0.98       121

    accuracy                           0.97       188
   macro avg       0.97      0.97      0.97       188
weighted avg       0.97      0.97      0.97       188

